[package]
name = "random-binary-search"
version = "0.1.0"
authors = ["Charlie Saunders <charlieasaunders@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
libmath = "0.2.1"
rand = "0.8.3"
